name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

#   strategy:
#     matrix:
#       node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: npm install, build, and test
      run: |
        yarn install --pure-lockfile
      env:
        CI: true
    - name: workaround for detached HEAD
      run: |
        git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
    - name: create the current snapshot
      run: |
        yarn test
    - name: run reg
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn run reg-suit run --test
